import { NavLink, Navigate, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { useEffect, useState } from 'react'
import { api } from './api'

const Icon = ({ children }) => <span className="icon">{children}</span>
const Loading = () => <div className="loading">Loading operational data…</div>
const navItems = [['/dashboard', '◫', 'Dashboard'], ['/analysis', '⊕', 'New analysis'], ['/history', '◷', 'History']]

function Shell({ children }) {
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="sonar-mark">◉</span><div><b>OCEANWATCH</b><small>MARINE DEBRIS INTELLIGENCE</small></div></div><nav>{navItems.map(([to, icon, label]) => <NavLink key={to} to={to}><Icon>{icon}</Icon>{label}</NavLink>)}</nav><div className="sidebar-note"><span className="pulse"/> SYSTEM ONLINE<br/><small>AI-assisted prototype</small></div></aside><main><header><div><p className="eyebrow">SIH 2026 · SIH26057</p><h1>AI-Powered Marine Debris Detection</h1></div><div className="live-status"><span className="pulse"/> Operational</div></header>{children}</main></div>
}

function StatCard({ label, value, accent, hint }) { return <div className={`stat-card ${accent || ''}`}><p>{label}</p><strong>{value}</strong><small>{hint}</small></div> }
function Dashboard() {
  const [data, setData] = useState(null); const [recent, setRecent] = useState([]); const [error, setError] = useState('')
  useEffect(() => { Promise.all([api.statistics(), api.analyses()]).then(([s, a]) => { setData(s); setRecent(a.slice(0, 5)) }).catch(e => setError(e.message)) }, [])
  if (error) return <div className="error">Unable to reach the backend: {error}</div>; if (!data) return <Loading />
  const high = data.detections_by_risk_level.HIGH || 0; const avg = recent.flatMap(x => x.detections).length ? recent.flatMap(x => x.detections).reduce((sum, x) => sum + x.confidence, 0) / recent.flatMap(x => x.detections).length : 0
  return <><section className="hero"><div><p className="eyebrow">UNDERWATER SURVEY OPERATIONS</p><h2>Detect. Prioritize.<br/><em>Protect.</em></h2><p>Process side-scan sonar imagery to identify and localize potential marine debris.</p><NavLink className="primary-btn" to="/analysis">Upload sonar image <span>→</span></NavLink></div><div className="sonar-visual"><div className="ring r1"/><div className="ring r2"/><div className="ring r3"/><span>LIVE<br/>SONAR<br/>ANALYSIS</span></div></section><section className="stats"><StatCard label="TOTAL ANALYSES" value={data.analysis_count} hint="Stored surveys"/><StatCard label="TOTAL DETECTIONS" value={data.detection_count} hint="After confidence filtering" accent="cyan"/><StatCard label="HIGH PRIORITY" value={high} hint="Requires review" accent="alert"/><StatCard label="AVERAGE CONFIDENCE" value={`${Math.round(avg * 100)}%`} hint="Recent analysis set"/></section><section className="panel"><div className="section-title"><div><p className="eyebrow">ACTIVITY LOG</p><h2>Recent analyses</h2></div><NavLink to="/history">View all →</NavLink></div><AnalysisTable rows={recent}/></section></>
}

function AnalysisTable({ rows }) { const navigate = useNavigate(); return rows.length ? <div className="table-wrap"><table><thead><tr><th>ANALYSIS</th><th>DATE / TIME</th><th>LOCATION</th><th>DETECTIONS</th><th>MODEL</th><th>STATUS</th></tr></thead><tbody>{rows.map(a => <tr key={a.id} onClick={() => navigate(`/results/${a.id}`)}><td><b>#{String(a.id).padStart(3, '0')}</b><small>{a.filename}</small></td><td>{new Date(a.created_at).toLocaleString()}</td><td><small>{a.latitude == null || a.longitude == null ? 'N/A' : `${a.latitude.toFixed(4)}, ${a.longitude.toFixed(4)}`}</small><small>{a.location_source === 'synthetic_demo' ? 'Synthetic Demo Location' : a.location_source === 'user_provided' ? 'User Provided Location' : 'N/A'}</small></td><td>{a.detections.length}</td><td><span className="model-chip">{a.model_mode === 'demo' ? 'PROTOTYPE DEMO' : 'YOLO'}</span></td><td><span className="status">● {a.status}</span></td></tr>)}</tbody></table></div> : <div className="empty">No analyses yet. Upload a side-scan sonar image to begin.</div> }

function AnalysisPage() {
  const navigate = useNavigate(); const [file, setFile] = useState(null); const [preview, setPreview] = useState(''); const [form, setForm] = useState({ confidence_threshold: .25, latitude: '', longitude: '', survey_id: '' }); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const choose = e => { const chosen = e.target.files?.[0]; if (!chosen) return; setFile(chosen); setPreview(URL.createObjectURL(chosen)) }
  const submit = async e => { e.preventDefault(); if (!file) return setError('Select a sonar image first.'); setBusy(true); setError(''); const payload = new FormData(); payload.append('image', file); Object.entries(form).forEach(([k,v]) => { if (v !== '') payload.append(k, v) }); try { const result = await api.analyze(payload); navigate(`/results/${result.id}`, { state: { result } }) } catch (err) { setError(err.message) } finally { setBusy(false) } }
  return <div className="analysis-grid"><section className="panel upload-panel"><p className="eyebrow">NEW MISSION ANALYSIS</p><h2>Upload Side-Scan Sonar Image</h2><form onSubmit={submit}><label className={`dropzone ${preview ? 'has-preview' : ''}`}><input type="file" accept=".png,.jpg,.jpeg,.tif,.tiff,image/png,image/jpeg,image/tiff" onChange={choose}/>{preview ? <img src={preview} alt="Selected sonar preview"/> : <><span className="upload-icon">⇧</span><b>Select image or drag it here</b><small>PNG, JPG, JPEG, TIFF · Max 20 MB</small></>}</label><div className="form-grid"><Field label="Confidence threshold" type="number" min="0" max="1" step="0.05" value={form.confidence_threshold} onChange={v => setForm({...form, confidence_threshold:v})}/><Field label="Survey ID" placeholder="e.g. BAY-2026-01" value={form.survey_id} onChange={v => setForm({...form, survey_id:v})}/><Field label="Latitude" type="number" step="any" placeholder="Optional" value={form.latitude} onChange={v => setForm({...form, latitude:v})}/><Field label="Longitude" type="number" step="any" placeholder="Optional" value={form.longitude} onChange={v => setForm({...form, longitude:v})}/></div>{error && <div className="error">{error}</div>}<button className="primary-btn full" disabled={busy}>{busy ? 'Analyzing sonar image…' : 'Analyze Sonar Image →'}</button></form></section><aside className="pipeline"><p className="eyebrow">PROCESS PIPELINE</p>{['UPLOAD','PREPROCESSING','AI DETECTION','FILTERING','COMPLETE'].map((step, index) => <div className={busy ? (index === 0 ? 'done' : 'active') : index === 0 && file ? 'done' : ''} key={step}><span>{busy && index > 0 ? '→' : index === 0 && file ? '✓' : index + 1}</span>{step}</div>)}<small>Progress updates only reflect the submitted analysis request; no simulated processing is shown.</small></aside></div>
}
function Field({ label, onChange, ...props }) { return <label className="field"><span>{label}</span><input {...props} onChange={e => onChange(e.target.value)}/></label> }

function Results() {
  const { id } = useParams(); const [analysis, setAnalysis] = useState(null); const [selected, setSelected] = useState(null); const [error, setError] = useState('')
  useEffect(() => { api.analysis(id).then(setAnalysis).catch(e => setError(e.message)) }, [id]); if (error) return <div className="error">{error}</div>; if (!analysis) return <Loading />
  const locationLabel = analysis.location_source === 'synthetic_demo' ? 'Synthetic Demo Location' : analysis.location_source === 'user_provided' ? 'User Provided Location' : 'N/A'; const location = analysis.latitude == null || analysis.longitude == null ? `${locationLabel} · N/A` : `${analysis.latitude.toFixed(5)}, ${analysis.longitude.toFixed(5)} · ${locationLabel}`; const imageCards = [['Original image', analysis.original_image_path], ['Processed image', analysis.processed_image_path], ['Annotated image', analysis.annotated_image_path]]
  return <><section className="results-head"><div><p className="eyebrow">ANALYSIS #{String(analysis.id).padStart(3, '0')} · {analysis.filename}</p><h2>Detection results</h2></div><div className={`mode-banner ${analysis.model_mode}`}><b>MODEL MODE: {analysis.model_mode === 'demo' ? 'PROTOTYPE DEMO' : 'YOLO'}</b><small>{analysis.model_mode === 'demo' ? 'Deterministic prototype output — not trained sonar AI.' : 'Custom YOLO weights active.'}</small></div></section><section className="summary"><StatCard label="TOTAL DETECTIONS" value={analysis.detections.length} hint="Above selected threshold"/><StatCard label="CONFIDENCE THRESHOLD" value={`${Math.round(analysis.confidence_threshold * 100)}%`} hint="Filter setting"/><StatCard label="SURVEY ID" value={analysis.survey_id || '—'} hint="Mission reference"/><StatCard label="LOCATION" value={analysis.latitude == null ? 'N/A' : 'SET'} hint={location}/></section><section className="image-grid">{imageCards.map(([label, path]) => <div className="image-card" key={label}><p>{label}</p><img src={api.imageUrl(path)} alt={label}/></div>)}</section><section className="results-layout"><div className="panel"><div className="section-title"><div><p className="eyebrow">IDENTIFIED OBJECTS</p><h2>Detection details</h2></div></div><div className="detections">{analysis.detections.map((d, i) => <button key={d.id} className={`detection ${selected?.id === d.id ? 'selected' : ''}`} onClick={() => setSelected(d)}><span className="detection-num">#{String(i+1).padStart(2,'0')}</span><div><b>{d.class_name}</b><small>Confidence: {Math.round(d.confidence*100)}% · {d.confidence_level}</small></div><span className={`risk ${d.risk_level.toLowerCase()}`}>{d.risk_level}</span></button>)}{!analysis.detections.length && <div className="empty">No detections met the selected confidence threshold.</div>}</div>{selected && <div className="bbox">Selected detection bounding box: <b>[{selected.bbox.join(', ')}]</b></div>}</div><aside className="panel location-panel"><p className="eyebrow">LOCATION</p><h2>{location}</h2><dl><dt>Latitude</dt><dd>{analysis.latitude ?? 'Unavailable'}</dd><dt>Longitude</dt><dd>{analysis.longitude ?? 'Unavailable'}</dd><dt>Survey ID</dt><dd>{analysis.survey_id || 'Unavailable'}</dd></dl><div className="report-actions"><a href={api.report(analysis.id, 'pdf')}>Download PDF</a><a href={api.report(analysis.id, 'json')}>Download JSON</a></div></aside></section></>
}
function History() { const [rows, setRows] = useState(null); const [error, setError] = useState(''); useEffect(() => { api.analyses().then(setRows).catch(e => setError(e.message)) }, []); return <section className="panel"><p className="eyebrow">ANALYSIS ARCHIVE</p><h2>Survey history</h2>{error ? <div className="error">{error}</div> : rows ? <AnalysisTable rows={rows}/> : <Loading/>}</section> }
function App() { return <Shell><Routes><Route path="/dashboard" element={<Dashboard/>}/><Route path="/analysis" element={<AnalysisPage/>}/><Route path="/results/:id" element={<Results/>}/><Route path="/history" element={<History/>}/><Route path="*" element={<Navigate to="/dashboard" replace/>}/></Routes></Shell> }
export default App
